@startuml

class MainActivity
class RegisterUser
class LoginActivity
class Transaction
class User
class FileSelectorFragment
class FileUtils
class HSBCRegex
interface PDFProcessor
class HSBCPDFProcessor
class AnalyticsFragment
class PagerAdapter
class RecyclerViewAdapter
class TransactionFragment
class ViewTransaction
class MyXAxisValueFormatter

class DashboardFragment
class AddToCategoryFragment
class MostRecentRVAdapter
class MoneyValueFormatter
class ValueFormatter
class PercentageValueFormatter
class ViewTransaction
class SummaryXFormatter
class Category


RegisterUser ..> MainActivity : calls
LoginActivity ..> MainActivity : calls
RegisterUser *-- User
MainActivity *-- PagerAdapter
PagerAdapter *-- TransactionFragment
PagerAdapter *-- AnalyticsFragment
PagerAdapter *-- FileSelectorFragment
AnalyticsFragment *-- MyXAxisValueFormatter
PDFProcessor o-- Transaction
FileSelectorFragment *-- PDFProcessor
FileSelectorFragment *-- FileUtils
HSBCPDFProcessor *-- HSBCRegex
TransactionFragment *-- RecyclerViewAdapter
TransactionFragment *-- ViewTransaction
PDFProcessor *-- HSBCPDFProcessor

PagerAdapter *-- DashboardFragment
DashboardFragment *-- SummaryXFormatter
DashboardFragment *-- MostRecentRVAdapter
TransactionFragment *-- ViewTransaction
ViewTransaction *-- AddToCategoryFragment
Transaction *-- Category

AnalyticsFragment *-- MoneyValueFormatter
AnalyticsFragment *-- PercentageValueFormatter

ValueFormatter <|-- MoneyValueFormatter
ValueFormatter <|-- PercentageValueFormatter
ValueFormatter <|-- MyXAxisValueFormatter





@enduml