@startuml
'https://plantuml.com/sequence-diagram

autonumber

group

alt register for a new account
User -> RegisterActivity: Submit credentials

RegisterActivity -> Firebase_Database : Register new user

Firebase_Database -> RegisterActivity : Response

alt success

RegisterActivity -> MainActivity: Call Activity

MainActivity --> User : Return Activity

else fail

RegisterActivity --> User : Register Fail

end


end

User -> LoginActivity: Submit login credentials

LoginActivity -> Firebase_Database: Authentication Request

Firebase_Database --> LoginActivity: Authentication Response

group authentication response

alt success

LoginActivity -> MainActivity: Call Activity

MainActivity --> User : Return Activity

else fail

LoginActivity --> User : Login Fail

end






@enduml