@startuml
'https://plantuml.com/sequence-diagram

autonumber

group

alt register for a new account
User -> RegisterActivity: Submit credentials

RegisterActivity -> Firebase_Authentication : Register new user

Firebase_Authentication -> RegisterActivity : Response

alt success

RegisterActivity -> MainActivity: Call Activity

MainActivity --> User : Return Activity

else fail

RegisterActivity --> User : Register Fail

end


end

User -> LoginActivity: Submit login credentials

LoginActivity -> Firebase_Authentication: Authentication Request

Firebase_Authentication --> LoginActivity: Authentication Response

group authentication response

alt success

LoginActivity -> MainActivity: Call Activity

MainActivity --> User : Return Activity

else fail

LoginActivity --> User : Login Fail

end






@enduml