@startuml
'https://plantuml.com/use-case-diagram




(Informed decision making) as (ifd)

package SpendingTracker {
    usecase (Monitor Family or multiple people finance) as (mf)
    usecase (View list of transactions with friendly user interface) as (frui)
    usecase (Monitor Finance)
    usecase (Export as Excel File)
    usecase (Categorise Transactions)
    usecase (Secure database storage of data)
    usecase (Query Transactions)
}

left to right direction

User --> (Monitor Finance)

(Monitor Finance) --> (mf)

(Monitor Finance) --> (frui)

User --> (Export as Excel File)

User --> (Categorise Transactions)

User --> (Query Transactions)

User --> (Secure database storage of data)

User --> (Open account on any device with the app)

(frui) --> (ifd)
(Export as Excel File) --> (ifd)
(Categorise Transactions) --> (ifd)
(Query Transactions) --> (ifd)

@enduml